name: bookqubit
description: "A book reading app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/
    - lib/screens/books/data/book_data.json
    - lib/screens/books/data/book_image_data.json
    
flutter_launcher_icons:
  android: true
  ios: false

  image_path: "assets/logo/bookqubitlogo1.png"

  min_sdk_android: 21

  adaptive_icon_background: "#5E2EFF"
  adaptive_icon_foreground: "assets/logo/bookqubitlogo1.png"